---
openapi: 3.0.1
info:
  title: Locations
  description: Locations API
  version: 1.0.0
paths:
  /locations:
    get:
      responses:
        200:
          description: Successfull response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/location'
              examples:
                all:
                  value: |-
                    [
                      {
                        "id": 1,
                        "name": "Kamarhati",
                        "type": "Regional Branch",
                        "status": "1",
                        "location": {
                          "lat": "-28.32555",
                          "lng": "-5.91531"
                        }
                      },
                      {
                        "id": 2,
                        "name": "Otranto",
                        "type": "Local Office",
                        "status": "1",
                        "location": {
                          "lat": "-8.01254",
                          "lng": "101.47364"
                        }
                      },
                      {
                        "id": 3,
                        "name": "Millesimo",
                        "type": "Headquarter",
                        "status": "1",
                        "location": {
                          "lat": "78.88435",
                          "lng": "99.05294"
                        }
                      }
                    ]
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
            examples:
              body:
                value: |-
                  {
                    "id": 101,
                    "name": "International Inc Canada",
                    "location": {
                      "lat": 43.6532,
                      "lng": 79.3832
                    },
                    "type": "Headquarter",
                    "status": "1"
                  }
        required: true
      responses:
        201:
          description: Sucessfully created
          content:
            application/json: {}
  /locations/{id}:
    get:
      responses:
        200:
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
              examples:
                getLocationID:
                  value: |-
                    {
                      "id": 1,
                      "name": "Kamarhati",
                      "type": "Regional Branch",
                      "status": "1",
                      "location": {
                        "lat": "-28.32555",
                        "lng": "-5.91531"
                      }
                    }
    parameters:
    - name: id
      in: path
      required: true
      schema:
        format: int32
        type: integer
  /location/phone/{id}:
    get:
      responses:
        200:
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
              examples:
                getLocationPhoneID:
                  value: |-
                    {
                      "id" : 4,
                      "operatingHour" : "8:00 AM - 5:00 PM",
                      "owner" : "XXX XXX",
                      "phone" : "345-678-9567"
                    }
    parameters:
    - name: id
      in: path
      required: true
      schema:
        format: int32
        type: integer
components:
  schemas:
    location:
      title: Root Type for location
      description: The root of the location type's schema.
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        type:
          type: string
        status:
          format: int32
          type: integer
        location:
          type: object
          properties:
            lat:
              type: string
            lng:
              type: string
      example: |-
        {
          "id": 1,
          "name": "Kamarhati",
          "type": "Regional Branch",
          "status": "1",
          "location": {
            "lat": "-28.32555",
            "lng": "-5.91531"
          }
        }
