---
- name: Process user namespace
  include_role:
    name: project
  vars:
    project: 'user{{ item }}'
    display_name: 'User{{ item }} Project'

- name: Process tools namespace
  include_role:
    name: project
  vars:
    project: 'tools{{ item }}'
    display_name: 'User{{ item }} Tools Project'
  when: user_tools_projects

- name: Give {{ item }} access to project
  shell: oc policy add-role-to-user admin user{{ item  }}