---

- name: Define Tools
  set_fact:
    tools_project: "tools-{{guid}}"  

- name: Define gogs version
  set_fact:
    gogs_version: "0.11.34"

- name: Define gogs user/pwd
  set_fact:
    gogs_userpwd: "gogs"


- name: Create project for workload; project =  {{tools_project}}
  shell: "oc new-project {{tools_project}}"

- name: Make sure we go back do default project
  shell: "oc project default"
  
- name: Create Gogs app
  shell: "oc new-app -f https://raw.githubusercontent.com/OpenShiftDemos/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml \
  -p GOGS_VERSION={{gogs_version}} \
  -p SKIP_TLS_VERIFY=true \
  -p HOSTNAME=gogs.{{ ocp_apps_domain }} \
  -n {{tools_project }}"

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{tools_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{tools_project}}"


- name: Wait until Gogs API is available 
  uri: 
    url: http://gogs.{{ocp_apps_domain}}
    method: GET
    follow_redirects: safe
    validate_certs: no
  register: wait_gogs_result
  until: wait_gogs_result is succeeded
  ignore_errors: yes
  retries: 15
  delay: 30

- name: Create Gogs users
  uri:
    url: http://gogs.{{ ocp_apps_domain}}/user/sign_up
    method: POST
    follow_redirects: safe
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "user_name={{gogs_userpwd}}&password={{gogs_userpwd}}&retype={{gogs_userpwd}}&email={{gogs_userpwd}}@example.com"
    validate_certs: no
    status_code: 200
  register: create_tenant_result
  ignore_errors: true


- debug: var=create_tenant_result

- name: Get Git Repo
  uri:
    url: 'https://raw.githubusercontent.com/weimeilin79/dayinthelife-integration/master/support/template/gogs.json'
    return_content: yes
  register: get_gitrepo
  
- debug: var=get_gitrepo.content


- name: Config repo
  uri: 
    url: 'http://gogs.{{ ocp_apps_domain }}/api/v1/repos/migrate'
    method: POST
    body: "{{ get_gitrepo.content }}"
    body_format: json
    user: "{{gogs_userpwd}}"
    password: "{{gogs_userpwd}}"
    headers:
      Content-Type: "application/json"
    force_basic_auth: yes
    return_content: yes
    validate_certs: no
    status_code: 201

   
- name: Create Jenkins
  shell: "oc new-app jenkins-ephemeral  \
  -n {{ tools_project }}"


- name: Create Nexus3
  shell: "oc new-app -f https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus3-template.yaml   \
  -p NEXUS_VERSION=3.12.1 \
  -p MAX_MEMORY=2Gi \
  -n {{ tools_project }}"


- name: Run Apicurio
  include: ./provision_apicurio.yml
  become: true 
