---
- name: post_workload Tasks Complete
  debug:
    msg: "Pre-Software checks completed successfully - Removed"

- name: define che_project
  set_fact:
    che_project: "rh-che-{{guid}}"

- name: Define sso
  set_fact:
    sso_project: "rh-sso-{{guid}}"

- name: Define Fuse Online
  set_fact:
    fuseonline_project: "fuse-online-{{guid}}"

- name: Define Tools
  set_fact:
    tools_project: "tools-{{guid}}"   
    
- name: Define 3scale
  set_fact:
    threescale_project: "rh-threescale-{{guid}}"    
    
- name: Define Apicurio
  set_fact:
    apicurio_project: "rh-apicurio-{{guid}}"
    
           
#- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{ocp_username}}-{{guid}}"
#  shell: oc delete clusterresourcequota clusterquota-{{ocp_username}}-{{guid}}
#  ignore_errors: true

#- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{ocp_username}}"
#  shell: oc delete clusterresourcequota clusterquota-{{ocp_username}}
#  ignore_errors: true

#===========================REMOVE================================

- name: Remove user Project che_project
  shell: "oc delete project {{che_project}}"
  ignore_errors: true

- name: Remove user Project sso_project
  shell: "oc delete project {{sso_project}}"
  ignore_errors: true
 
- name: Remove user Project fuseonline_project
  shell: "oc delete project {{fuseonline_project}}"
  ignore_errors: true
 
- name: Remove user Project tools_project
  shell: "oc delete project {{tools_project}}"
  ignore_errors: true

- name: Remove user Project threescale_project
  shell: "oc delete project {{threescale_project}}"
  ignore_errors: true


 
#=================================================================
- name: post_workload Tasks Complete
  debug:
    msg: "Post-Software checks completed successfully - Removed"
