---

- name: Run Che Setup
  include: ./provision_che.yml
  become: true
  ignore_errors: true

- name: Run Red Hat SSO Setup
  include: ./provision_sso.yml
  become: true
  ignore_errors: true

- name: Run Red Hat Fuse Online
  include: ./provision_fuseonline.yml
  become: true
  ignore_errors: true

- name: Run Tools
  include: ./provision_tools.yml
  become: true
  ignore_errors: true

- name: Run 3scale
  include: ./provision_threescale.yml
  become: true
  ignore_errors: true
  
- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete

  
