---

- name: Run Che Setup
  include: ./provision_che.yml
  become: false

- name: Run Red Hat SSO Setup
  include: ./provision_sso.yml
  become: false
 
- name: Run Red Hat Fuse Online
  include: ./provision_fuseonline.yml
  become: false

- name: Run Tools
  include: ./provision_tools.yml
  become: false  

- name: Run 3scale
  include: ./provision_threescale.yml
  become: false  


  
- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete

  