---
- name: Make sure we go back to default project
  shell: "oc project default"

- name: Create the 3scale app
  shell: "oc new-app \
  -f {{ threescale_template_url }} \
  --param WILDCARD_DOMAIN={{ ocp_apps_domain }} --param ADMIN_PASSWORD=password --param WILDCARD_POLICY=Subdomain \
  --param ADMIN_ACCESS_TOKEN={{threescale_admin_access_token}} --param MASTER_PASSWORD=password --param MASTER_ACCESS_TOKEN={{threescale_master_access_token}} -n {{ namespace }}"
  register: create_3scale_cmd
  failed_when: create_3scale_cmd.stderr != '' and 'already exists' not in create_3scale_cmd.stderr
  when: configure_only == 'false'

- name: Wait until 3scale API is available 
  uri: 
    url: https://master-admin.{{ ocp_apps_domain }}
    method: HEAD
    validate_certs: no
  register: wait_threescale_result
  until: wait_threescale_result is succeeded
  ignore_errors: yes
  retries: 10
  delay: 60
  when: create_tenants

- name: Create tenants
  include_tasks: ./create-tenants.yml
  with_sequence: start=1 end={{ usersno }} format=user%d
  when: create_tenants

- name: Create apikey service
  include_tasks: ./create-service.yml
  vars:
    admintoken: '{{threescale_admin_access_token}}'
    account_id: '3'
    name: 'Location API'
    backend_version: '1'
    configure_only: '{{no_threescale_services}}'
    system_name: 'location-api'
    proxy_config: 
      production_endpoint: 'https://location-api.amp.{{ ocp_apps_domain }}:443'
      staging_endpoint: 'https://location-api-staging.amp.{{ ocp_apps_domain }}:443'
      backend_endpoint: 'http://location-service-{{ backend_project }}.{{ ocp_apps_domain }}:80'
    application_plan:
      name: 'Simple'
      system_name: 'simple'
    app_config:
      id: 'www-app'
      name: 'Webapp'
      description: 'Simple WebApp'

- name: Get SSO Token Longer Lifespan
  uri:
    url: "https://secure-sso-{{sso_project}}.{{ocp_apps_domain}}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ eval_rhsso_admin_username | default('keyadmin') }}"
      password: "{{ eval_rhsso_admin_password | default('keypassword') }}"
      grant_type: password
      client_id: admin-cli
    return_content: yes
    validate_certs: no
  retries: 10
  delay: 60
  until: token_text is succeeded
  register: token_text

- name: Set TKN var
  set_fact:
    TKN: "{{ token_text.json.access_token }}"

- name: Get id for 3scale-client
  uri:
    url: "https://secure-sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms/{{threescale_realm}}/clients"      
    headers:
      Authorization: "Bearer {{TKN}}"
    return_content: yes
    validate_certs: no
  retries: 10
  delay: 60
  until: clients_text is succeeded
  register: clients_text

- name: Select client id
  set_fact:
    IdClientAdmin: "{{ item.id }}"
  when:
    - item.clientId == (threescale_client_id | default('3scale-admin'))
    - IdClientAdmin is undefined
  with_items: "{{ clients_text.json }}"

- debug: var=IdClientAdmin

- name: Get client secret
  uri:
    url: "https://secure-sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms/{{threescale_realm}}/clients/{{ IdClientAdmin }}/client-secret"
    headers:
      Authorization: "Bearer {{TKN}}"
  register: secret_text

- name: Set client_secret var
  set_fact: client_secret={{ secret_text.json.value }}

- debug: var=client_secret

- name: Create sso service
  include_tasks: ./create-service.yml
  vars:
    admintoken: '{{ threescale_admin_access_token }}'
    account_id: '3'
    name: 'SSO Location API'
    backend_version: 'oidc'
    system_name: 'location-sso'
    configure_only: '{{no_threescale_services}}'
    proxy_config: 
      production_endpoint: 'https://location-sso.amp.{{ ocp_apps_domain }}:443'
      staging_endpoint: 'https://location-sso-staging.amp.{{ ocp_apps_domain }}:443'
      backend_endpoint: 'http://location-service-{{ backend_project }}.{{ ocp_apps_domain }}:80'
      sso_endpoint: 'http://{{threescale_client_id | default("3scale-admin")}}:{{ client_secret }}@sso-{{ sso_project }}.{{ ocp_apps_domain }}/auth/realms/{{threescale_realm | default("threescale")}}'
    application_plan:
      name: 'Secure'
      system_name: 'secure'
    app_config:
      id: 'www-secured'
      name: 'Secured App'
      description: 'SSO Secured App'
      redirect_uri: 'http://www-{{ backend_project }}.{{ ocp_apps_domain }}/*'

- name: Get id for client 'www-secured'
  uri:
    url: 'https://secure-sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms/{{threescale_realm | default("threescale")}}/clients'
    return_content: yes
    headers:
      Authorization: 'Bearer {{TKN}}'
    validate_certs: no
  register: client_text
  until: "'www-secured' in client_text.content"
  retries: 20
  delay: 30

- name: Set IdClientApp var
  set_fact: IdClientApp={{ client_text.json | json_query(query) }}
  vars:
    query: "[?clientId=='www-secured'] | [0].id"

- debug: var=IdClientApp

- name: Update the rh sso app
  uri: 
    url: "https://secure-sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms/{{threescale_realm}}/clients/{{IdClientApp}}"
    method: PUT
    return_content: yes
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{TKN}}"
    body: '{ "clientId": "www-secured", "publicClient" : "true", "rootUrl": "http://www-{{ backend_project }}.{{ ocp_apps_domain }}", "baseUrl": "/" }'
    body_format: json
    validate_certs: no
    status_code: 204
  retries: 10
  delay: 60
  until: update_app_result is succeeded
  register: update_app_result

- debug: var=update_app_result

- include_tasks: create-wildcard-route.yml
  when: create_wildcard_route

- name: Make sure we go back to default project
  shell: "oc project default"
